### ISSUE TITLE
Cranelift does have trunc, zext and sext equivalents

### ISSUE THREAD

**Issue by bjorn3** [jubitaneja/codegen#1]
https://github.com/jubitaneja/codegen/blob/823d63de36460141968778b3a6cf506d76f47b07/discuss.txt#L28-L29

They are called `ireduce`, `uextend` and `sextend`.

**Comment by jubitaneja** [comment]
Thanks for the clarification. I have not updated some stuff in this repository for a while, but it's good time to add these instructions now. :)
